Blog/urls.py
from django.urls import path, include

app_name = "Blog"
urlpatterns = [path("api/v1/", include("Blog.api.v1.urls"), name="api")]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="This is Blog api",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="mohamadimahdieh70@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("Home.urls")),
    path("account/", include("account.urls"), name="account"),
    path("Blog/", include("Blog.urls"), name="Blog"),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "swagger/Blog.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, include
from .views import RegisterUser, LoginUser

app_name = "account"

urlpatterns = [
    path("register", RegisterUser.as_view(), name="register"),
    path("login", LoginUser.as_view(), name="login"),
    path("api/v1/", include("account.api.v1.urls"), name="api"),
]

templates/includes/footer_refrence.html
{% load static %}

<!-- =========================================js login====================================================== -->
<!-- <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script> -->
<!-- ========================================================================================================= -->

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

templates/includes/footer_tag.html
<div class="container py-4 bg-secondary text-center">
    <p class="m-0 text-white">
        &copy; <a class="text-white font-weight-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed by <a
            class="text-white font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
    </p>
</div>

templates/includes/head_refrence.html
{% load static %}
<meta charset="utf-8">
<title> Personal Blog</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Mahdieh Mohammadi" name="author">
<meta content="Personal Blog" name="keywords">
<meta content="Personal Blog" name="description">

<!-- Favicon -->
<link href="{% static 'img/favicon.ico' %}" rel="icon">
<!-- Google Fonts -->


<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<!--===============================================================================================-->
<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
<!--===============================================================================================-->

<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->

templates/includes/header_tag.html
<div class="container p-0">
    <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
        <a href="" class="navbar-brand d-block d-lg-none">Navigation</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav m-auto">
                <a href="index.html" class="nav-item nav-link active">Home</a>
                <a href="about.html" class="nav-item nav-link">About</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="single.html" class="dropdown-item">Blog Detail</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">account</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'account:register' %}" class="dropdown-item">Register</a>
                        <a href="{% url 'account:login' %}" class="dropdown-item">Login</a>
                        <a href="single.html" class="dropdown-item">Logout</a>
                    </div>
                </div>

            </div>
        </div>
    </nav>
</div>

templates/includes/sidebar.html
{% load static %}
<div class="sidebar">
    <div class="sidebar-text d-flex flex-column h-100 justify-content-center text-center">
        <img class="mx-auto d-block w-75 bg-primary img-fluid rounded-circle mb-4 p-3" src="{{object_user.image.url}}"
            alt="Image">
        <h4 class="font-weight-bold">{{object_user.first_name}}</h4>
        <p class="mb-4">
            Justo stet no accusam stet invidunt sanctus magna clita vero eirmod, sit sit labore dolores lorem. Lorem at
            sit dolor dolores sed diam justo
        </p>
        <div class="d-flex justify-content-center mb-5">
            <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-twitter"></i></a>
            <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
            <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
            <a class="btn btn-outline-primary mr-2" href="#"><i class="fab fa-instagram"></i></a>
        </div>
        <a href="" class="btn btn-lg btn-block btn-primary mt-auto">Hire Me</a>
    </div>
    <div class="sidebar-icon d-flex flex-column h-100 justify-content-center text-right">
        <i class="fas fa-2x fa-angle-double-right text-primary"></i>
    </div>
</div>